version: 2

seeds:
  - name: taxi_zone_lookup
    description: "Lookup seed for taxi zones in NYC"
    columns:
      - name: LocationID
        description: "Unique identifier for each taxi zone"
      - name: Borough
        description: "Borough where the taxi zone is located"
      - name: Zone
        description: "Name of the taxi zone"
      - name: service_zone
        description: "Service zone classification for the taxi zone"
        
