version: 2

models:
  - name: dim_vendors
    description: "Dimension table for taxi vendors"
    columns:
      - name: vendor_id
        description: "Unique identifier for each vendor"
      - name: vendor_name
        description: "Name of the taxi vendor"
  - name: dim_zones
    description: "Dimension table for taxi zones"
  - name: fct_trips
    description: "Fact table for taxi trips"
    columns:
      - name: payment_type
        data_tests:
          - accepted_values:
              values: [1, 2, 3, 4,5]
              quote: false